source 'https://github.com/CocoaPods/Specs.git'

target 'BAHVimeoOAuth', :exclusive => true do
  pod "BAHVimeoOAuth", :path => "../"
  pod 'AFNetworking', '~> 2.5'

end

target 'Tests', :exclusive => true do
  pod "BAHVimeoOAuth", :path => "../"
  pod 'AFNetworking', '~> 2.5'


  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
